version: "3.2"
services:
  autorizador:
    build: autorizador
    container_name: autorizador-experiment
    working_dir: /backend/
    volumes:
      - ./autorizador/:/mnt/
    environment:
      PYTHONUNBUFFERED: 1
      BD_PATH: 'sqlite:////mnt/autorizador.db'
    command: /bin/sh -c 'python build_database.py && python app.py'

  usuarios:
    build: usuarios
    container_name: usuarios-experiment
    working_dir: /backend/
    volumes:
      - ./usuarios/:/mnt/
    environment:
      PYTHONUNBUFFERED: 1
      BD_PATH: 'sqlite:////mnt/usuarios.db'
    command: /bin/sh -c 'python build_database.py && python api.py'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - autorizador
        - usuarios